version: '3'

env:
  COMPOSE_FILE: .dev/compose.yaml

tasks:

  # dev environment

  dev:
    desc: Run dev environment.
    cmds:
      - task: docker:build
      - docker compose run --rm dev

  docker:build:
    internal: true
    run: once
    sources:
      - .dev/Dockerfile
      - .dev/compose.yaml
      - .dev/requirements-dev.txt
      - .dev/requirements-res.txt
    cmds:
      - docker compose build

  # host commands

  research:
    desc: Test original syntax implementations.
    cmds:
      - task: research:dc243
      - task: research:genv

  research:*:
    vars: {SYNTAX: '{{index .MATCH 0}}'}
    label: 'research:{{.SYNTAX}}'
    sources:
      - research/syntax.py
      - research/test_{{.SYNTAX}}.py
    cmds:
      - task: docker:build
      - docker compose run --rm research-{{.SYNTAX}} pytest -x test_{{.SYNTAX}}.py

  clean:
    desc: Clean all builder artefacts.
    cmds:
      - rm -rf build-* subprojects
      - docker compose down --rmi local --volumes

  # dev commands

  run:
    desc: Run target executable.
    vars: {BTYPE: release}
    cmds:
      - task: build:release
      - build-{{.BTYPE}}/vsub {{.CLI_ARGS}}

  test:
    desc: Run tests.
    cmds:
      - task: build:release
      - pytest -x tests

  debug:
    desc: Run debugger.
    cmds:
      - task: build:debug
      - gdb --tui build-debug/vsub

  build:
    desc: Build debug and release.
    cmds:
      - task: build:release
      # if debug is needed, build with build:debug

  build:*:
    desc: Build debug or release.
    vars: {BTYPE: '{{index .MATCH 0}}'}
    cmds:
      - task: setup:wrapdb
      - task: setup:build:{{.BTYPE}}
      - task: generate:parsers
      - meson compile -C build-{{.BTYPE}}
      - '{{if eq .BTYPE "release"}}meson install -C build-{{.BTYPE}}{{end}}'

  version:
    desc: Bump project version > task version -- bump minor
    cmds:
      - bump-my-version {{.CLI_ARGS}}

  # generate

  generate:parsers:
    internal: true
    sources: [src/syntax/*/parser.peg]
    cmds:
      - cmd: packcc {{.ITEM}}
        for: sources

  # setup steps

  setup:wrapdb:
    internal: true
    status:
      - test -f subprojects/wrapdb.json
    cmds:
      - meson wrap update-db

  setup:build:*:
    internal: true
    vars: {BTYPE: '{{index .MATCH 0}}'}
    sources: [meson.build]
    generates: ['build-{{.BTYPE}}/**/*']
    cmds:
      - meson setup build-{{.BTYPE}} --buildtype={{.BTYPE}}
