/* A packrat parser generated by PackCC 2.0.2 */

#ifndef PCC_INCLUDED_PARSER_H
#define PCC_INCLUDED_PARSER_H

#include "../../syntax.h"
#define aux auxil

#ifdef __cplusplus
extern "C" {
#endif

typedef struct vsub_sx_default_context_tag vsub_sx_default_context_t;

vsub_sx_default_context_t *vsub_sx_default_create(Auxil *auxil);
int vsub_sx_default_parse(vsub_sx_default_context_t *ctx, char **ret);
void vsub_sx_default_destroy(vsub_sx_default_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_PARSER_H */
