%prefix "vsub_sx_default"
%auxil "Auxil *"
%value "const char *"
%common {
#include "../../aux.h"
}

input <- atom* !.

atom  <- '$$'                     { USE(Const("$")) }
       / '${' v:var '}'           { IF(Set(v)) THEN(Value) ELSE(Input) }
       / '$' v:var                { IF(Set(v)) THEN(Value) ELSE(Input) }
       / .                        { USE(Input) }

var <- <[_a-zA-Z] [_a-zA-Z0-9]*>  { $$ = $1; }
