%prefix "vsub_sx_default"
%auxil "Auxil *"
%value "char *"
%common {
#include "../../syntax.h"
#define aux auxil
}

input <- atom* EOS
atom  <- braced
       / simple
       / !EOS .                   { USE(Input) }

braced <- '${' var:var '}'        { IF(Set) THEN(Value) ELSE(Input) }
simple <- '$' var:var             { IF(Set) THEN(Value) ELSE(Input) }

var <- <[_a-zA-Z] [_a-zA-Z0-9]*>  { $$ = $1; }

EOS  <- '\0'
