services:

  dev:
    build: .
    hostname: vsub-dev
    stdin_open: true
    tty: true
    volumes:
      - ccache_data:/root/.ccache
      - ../:/build

  research-dc243:
    build:
      context: .
      target: research-dc243
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../tests/research/test_dc243.py:/research/test_dc243.py:ro

volumes:
  ccache_data:
