services:

  dev:
    build:
      context: .
      target: dev
    hostname: vsub-dev
    stdin_open: true
    tty: true
    volumes:
      - ccache_data:/root/.ccache
      - ../:/build

  research-dc243:
    build:
      context: .
      target: research-dc243
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../research:/research

  research-genv:
    build:
      context: .
      target: research-genv
    stdin_open: true
    tty: true
    volumes:
      - ../research:/research

volumes:
  ccache_data:
